const os=require('os');
const crypto=require('crypto');
const store=require('./local-store');
const cipher=require('./sync-crypto');
let running=null,pollTimer=null,debounceTimer=null,lastError='';
function legacy(){return require('./cloud-sync');}
function config(){return legacy().loadCloudConfig();}
function spaceId(){const cfg=config(),key=cipher.status().keyId;return crypto.createHash('sha256').update(`${String(cfg.url||'').replace(/\/+$/,'').toLowerCase()}|${cfg.userId||cfg.username}|${key}`).digest('hex');}
function aad(op){return{opId:op.opId,entityType:op.entityType,entityId:op.entityId,contentHash:op.contentHash,deleted:Boolean(op.deleted)}}
function deviceCredentials(space=spaceId()){const deviceId=store.getMeta('device_id');const key=`device_token:${space}`;let deviceToken=store.getMeta(key);if(!deviceToken){deviceToken=crypto.randomBytes(32).toString('base64url');store.setMeta(key,deviceToken)}return{deviceId,deviceToken}}
async function request(method,path,body){const cfg=config();if(!cfg.url||!cfg.token)throw new Error('未登录');const headers={'Content-Type':'application/json',Authorization:`Bearer ${cfg.token}`};if(!cipher.status().locked){const credentials=deviceCredentials();headers['X-RanPak-Device-ID']=credentials.deviceId;headers['X-RanPak-Device-Token']=credentials.deviceToken}const response=await fetch(`${cfg.url.replace(/\/+$/,'')}${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let result;try{result=await response.json()}catch{throw new Error(`同步服务返回无效响应 HTTP ${response.status}`)}if(result.code!==200)throw Object.assign(new Error(result.message||'同步失败'),{code:result.code,status:response.status});return result.data;}
async function ensureDevice(space){const status=cipher.status();if(status.locked)throw new Error('请先创建或导入恢复密钥');if(store.getMeta('canonical_migration_v2')!=='done')throw new Error('本地数据迁移尚未成功，已禁止同步');store.ensureBaseline(space);const{deviceId,deviceToken}=deviceCredentials(space);await request('POST','/api/sync/v2/devices',{deviceId,deviceToken,name:os.hostname(),keyId:status.keyId});return deviceId;}
async function pull(space){let cursor=store.getCursor(space),applied=0,conflictCount=0;do{const batch=await request('GET',`/api/sync/v2/pull?cursor=${cursor}`);for(const op of batch.operations||[]){const value=cipher.decrypt(op.envelope,aad(op));if(store.hash(JSON.stringify(value===undefined?null:value))!==op.contentHash)throw new Error(`同步内容校验失败: ${op.opId}`);const result=store.applyRemote(space,op,value);if(result.applied)applied++;if(result.conflict)conflictCount++;cursor=Math.max(cursor,Number(op.seq));}store.setCursor(space,cursor);if(!batch.hasMore)break;}while(true);return{applied,conflicts:conflictCount,cursor};}
async function push(space,deviceId){let pushed=0;while(true){const rows=store.pending(space,500);if(!rows.length)break;const operations=rows.map(row=>{const op={opId:row.op_id,deviceId,entityType:row.entity_type,entityId:row.entity_id,parentOpId:row.parent_op_id||'',mergeParents:JSON.parse(row.merge_parents||'[]'),contentHash:row.content_hash,deleted:Boolean(row.deleted)};return{...op,envelope:cipher.encrypt(store.payloadOf(row),aad(op))};});const result=await request('POST','/api/sync/v2/push',{deviceId,operations});for(const[id,seq]of Object.entries(result.accepted||{})){store.markSynced(space,id,seq);pushed++;}if(rows.length<500)break;}return pushed;}
async function runSync(){if(running)return running;running=(async()=>{const space=spaceId();try{const deviceId=await ensureDevice(space);const first=await pull(space);const pushed=await push(space,deviceId);const second=await pull(space);await request('POST','/api/sync/v2/activate',{});store.setMeta(`sync_protocol:${space}`,'2');lastError='';return{protocolVersion:2,syncSpaceId:space,pushed,applied:first.applied+second.applied,conflicts:first.conflicts+second.conflicts,cursor:second.cursor};}catch(error){lastError=error.message;throw error;}finally{running=null;}})();return running;}
function schedule(delay=1200){if(!legacy().isLoggedIn()||cipher.status().locked)return;clearTimeout(debounceTimer);debounceTimer=setTimeout(()=>runSync().catch(e=>console.error('[cloud-sync-v2]',e.message)),delay);}
function startPolling(interval=30000){stopPolling();if(!legacy().isLoggedIn()||cipher.status().locked)return;pollTimer=setInterval(async()=>{try{const status=await request('GET','/api/sync/v2/status');const space=spaceId();if(Number(status.latestCursor||0)>store.getCursor(space)||store.pending(space,1).length)await runSync();}catch(error){lastError=error.message;}},interval);}
function stopPolling(){if(pollTimer)clearInterval(pollTimer);if(debounceTimer)clearTimeout(debounceTimer);pollTimer=null;debounceTimer=null;}
async function devices(){return request('GET','/api/sync/v2/devices')}
async function revoke(id){return request('DELETE',`/api/sync/v2/devices/${encodeURIComponent(id)}`)}
async function reset(){const space=spaceId();const value=await request('DELETE','/api/sync/v2/space');store.resetSyncSpace(space);store.setMeta(`sync_protocol:${space}`,'0');return value;}
function status(){const space=!cipher.status().locked&&config().url?spaceId():'';return{syncing:Boolean(running),syncSpaceId:space,cursor:space?store.getCursor(space):0,pendingCount:space?store.pending(space,501).length:0,lastError};}
module.exports={sync:runSync,schedule,startPolling,stopPolling,devices,revoke,reset,status,spaceId};
