const path=require('path');
const fs=require('fs');
const appConfig=require('./config');
const store=require('./local-store');

const DEFAULT_TOOLS_CONFIG={ffmpeg:{ffmpegPath:'',ffprobePath:''},meme:{binaryPath:'',port:2233},live2d:{assetsDir:'',catalogPath:''},ai:{baseUrl:'',apiKey:'',model:''},featureVisibility:{hiddenFeatures:[]}};
const cleanPath=value=>String(value||'').trim();
function normalizeConfig(config={}){return{ffmpeg:{...DEFAULT_TOOLS_CONFIG.ffmpeg,...(config.ffmpeg||{}),ffmpegPath:cleanPath(config.ffmpeg?.ffmpegPath),ffprobePath:cleanPath(config.ffmpeg?.ffprobePath)},meme:{...DEFAULT_TOOLS_CONFIG.meme,...(config.meme||{}),binaryPath:cleanPath(config.meme?.binaryPath),port:Number(config.meme?.port)||2233},live2d:{...DEFAULT_TOOLS_CONFIG.live2d,...(config.live2d||{}),assetsDir:cleanPath(config.live2d?.assetsDir),catalogPath:cleanPath(config.live2d?.catalogPath)},ai:{...DEFAULT_TOOLS_CONFIG.ai,...(config.ai||{}),baseUrl:cleanPath(config.ai?.baseUrl),apiKey:cleanPath(config.ai?.apiKey),model:cleanPath(config.ai?.model)},featureVisibility:{hiddenFeatures:Array.isArray(config.featureVisibility?.hiddenFeatures)?config.featureVisibility.hiddenFeatures.filter(k=>typeof k==='string'):[]}};}
function readToolsConfig(){return normalizeConfig({ffmpeg:store.get('app_config','ffmpeg'),meme:store.get('app_config','meme'),live2d:store.get('app_config','live2d'),ai:store.get('app_config','ai'),featureVisibility:store.get('app_config','feature_visibility')});}
function writeToolsConfig(next={}){const current=readToolsConfig();const merged=normalizeConfig({ffmpeg:{...current.ffmpeg,...(next.ffmpeg||{})},meme:{...current.meme,...(next.meme||{})},live2d:{...current.live2d,...(next.live2d||{})},ai:{...current.ai,...(next.ai||{})},featureVisibility:current.featureVisibility});store.transaction(()=>{for(const id of ['ffmpeg','meme','live2d','ai'])store.put('app_config',id,merged[id]);});return merged;}
function validateExistingPath(file,label){const value=cleanPath(file);if(value&&!fs.existsSync(value))throw new Error(`${label} 不存在: ${value}`);return value;}
function validateToolsConfig(config=readToolsConfig()){const n=normalizeConfig(config);validateExistingPath(n.ffmpeg.ffmpegPath,'ffmpeg');validateExistingPath(n.ffmpeg.ffprobePath,'ffprobe');validateExistingPath(n.live2d.assetsDir,'Live2D 资源目录');validateExistingPath(n.live2d.catalogPath,'Live2D catalog');return n;}
function resolveFfmpegBins(config=readToolsConfig()){return{ffmpeg:cleanPath(config.ffmpeg?.ffmpegPath)||process.env.RAN_PAK_FFMPEG_PATH||'ffmpeg',ffprobe:cleanPath(config.ffmpeg?.ffprobePath)||process.env.RAN_PAK_FFPROBE_PATH||'ffprobe'};}
function resolveLive2dAssetsDir(config=readToolsConfig()){return cleanPath(config.live2d?.assetsDir)||appConfig.USER_LIVE2D_DIR;}
function resolveLive2dCatalogPath(config=readToolsConfig()){return cleanPath(config.live2d?.catalogPath)||path.join(resolveLive2dAssetsDir(config),'model-catalog.json');}
function encodeAssetPath(value=''){return String(value).replace(/\\/g,'/').split('/').filter(Boolean).map(encodeURIComponent).join('/');}
function toLive2dAssetUrl(value){const raw=String(value||'').trim().replace(/\\/g,'/');if(!raw||/^(https?:|data:|blob:)/i.test(raw)||raw.startsWith('/live2d-assets/'))return raw;return `/live2d-assets/${encodeAssetPath(raw.replace(/^\/?vendor\/live2d-widget\//,'').replace(/^\/+/,''))}`;}
function readLive2dCatalog(config=readToolsConfig()){const catalog=resolveLive2dCatalogPath(config),assets=resolveLive2dAssetsDir(config);if(!fs.existsSync(assets))throw Object.assign(new Error('Live2D 资源目录不存在，请先在设置中配置'),{statusCode:404});if(!fs.existsSync(catalog))throw Object.assign(new Error('Live2D catalog 不存在，请先在设置中配置'),{statusCode:404});const parsed=JSON.parse(fs.readFileSync(catalog,'utf8'));if(!Array.isArray(parsed))throw new Error('Live2D catalog 必须是数组');return parsed.map((model,index)=>({...model,id:index,message:model.message||model.name||`Live2D ${index+1}`,paths:(model.paths||[]).map(toLive2dAssetUrl).filter(Boolean),cover:model.cover?toLive2dAssetUrl(model.cover):'',textures:Number(model.textures||(model.paths||[]).length||1)})).filter(model=>model.paths.length);}
function readFeatureVisibility(){return store.get('app_config','feature_visibility')||{hiddenFeatures:[]};}
function writeFeatureVisibility(value={}){const next={hiddenFeatures:Array.isArray(value.hiddenFeatures)?value.hiddenFeatures.filter(k=>typeof k==='string'):[]};store.put('app_config','feature_visibility',next);return next;}
module.exports={DEFAULT_TOOLS_CONFIG,readToolsConfig,writeToolsConfig,validateToolsConfig,resolveFfmpegBins,resolveLive2dAssetsDir,resolveLive2dCatalogPath,readLive2dCatalog,readFeatureVisibility,writeFeatureVisibility};
