import {
  Camera,
  Clock,
  Crop,
  DataAnalysis,
  Files,
  Headset,
  MagicStick,
  Microphone,
  Mute,
  Picture,
  RefreshRight,
  VideoCamera,
} from '@element-plus/icons-vue'

export const videoToolModules = [
  {
    key: 'convert',
    label: '视频转换',
    navLabel: '视频转换',
    icon: RefreshRight,
    summary: '把视频转换成 MP4、WebM、MKV 等常见格式。',
    primaryAction: '开始转换',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', crf: 23, preset: 'medium' },
    fields: ['container', 'quality'],
  },
  {
    key: 'compress',
    label: '视频压缩',
    navLabel: '视频压缩',
    icon: VideoCamera,
    summary: '减小视频体积，适合上传、分享和归档。',
    primaryAction: '开始压缩',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', crf: 28, preset: 'medium', resolution: '1280x720' },
    fields: ['compressLevel', 'resolution'],
  },
  {
    key: 'trim',
    label: '时长裁剪',
    navLabel: '时长裁剪',
    icon: Clock,
    summary: '输入开始和结束时间，快速截取片段。',
    primaryAction: '截取片段',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', startTime: '00:00:00', endTime: '' },
    fields: ['timeRange'],
  },
  {
    key: 'extract-audio',
    label: '提取音频',
    navLabel: '提取音频',
    icon: Headset,
    summary: '从视频中导出 MP3、AAC、Opus 音频。',
    primaryAction: '导出音频',
    multi: false,
    defaults: { container: 'mp3', audioCodec: 'libmp3lame', audioBitrate: '192k' },
    fields: ['audioFormat', 'audioBitrate'],
  },
  {
    key: 'snapshot',
    label: '视频截图',
    navLabel: '视频截图',
    icon: Camera,
    summary: '按指定时间点导出视频画面。',
    primaryAction: '导出截图',
    multi: false,
    defaults: { container: 'image2', imageFormat: 'jpg', startTime: '00:00:01', quality: 2 },
    fields: ['snapshotTime', 'imageFormat'],
  },
  {
    key: 'concat',
    label: '合并视频',
    navLabel: '合并视频',
    icon: Files,
    summary: '按选择顺序合并多个视频文件。',
    primaryAction: '开始合并',
    multi: true,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', crf: 23, preset: 'medium' },
    fields: ['concatOrder', 'container'],
  },
  {
    key: 'watermark',
    label: '添加水印',
    navLabel: '添加水印',
    icon: MagicStick,
    summary: '添加文字水印，可设置位置、大小和颜色。',
    primaryAction: '添加水印',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', watermarkText: 'RanPak', watermarkPosition: 'leftTop', watermarkSize: 28, watermarkColor: 'white' },
    fields: ['watermark'],
  },
  {
    key: 'probe',
    label: '视频信息',
    navLabel: '视频信息',
    icon: DataAnalysis,
    summary: '查看时长、分辨率、编码、音轨、字幕等信息。',
    primaryAction: '读取信息',
    multi: false,
    infoOnly: true,
    defaults: {},
    fields: ['probe'],
  },
  {
    key: 'subtitle',
    label: '字幕处理',
    navLabel: '字幕处理',
    icon: Microphone,
    summary: '烧录字幕或保留字幕轨道。',
    primaryAction: '处理字幕',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', subtitlePath: '', subtitleMode: 'burn' },
    fields: ['subtitle'],
  },
  {
    key: 'resize-rotate',
    label: '旋转缩放',
    navLabel: '旋转缩放',
    icon: Crop,
    summary: '调整视频尺寸、帧率或旋转角度。',
    primaryAction: '应用调整',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'libx264', audioCodec: 'aac', resolution: 'source', rotate: 0, fps: 0 },
    fields: ['resolution', 'rotate', 'fps'],
  },
  {
    key: 'remove-audio',
    label: '去除音频',
    navLabel: '去除音频',
    icon: Mute,
    summary: '导出无声音的视频文件。',
    primaryAction: '去除音频',
    multi: false,
    defaults: { container: 'mp4', videoCodec: 'copy' },
    fields: ['container'],
  },
  {
    key: 'gif-speed-batch',
    label: 'GIF / 倍速 / 批量',
    navLabel: 'GIF/倍速/批量',
    icon: Picture,
    summary: '制作 GIF、调整播放速度，或使用同一设置批量处理。',
    primaryAction: '开始处理',
    multi: true,
    defaults: { subMode: 'gif', container: 'gif', fps: 12, width: 480, speed: 1, videoCodec: 'libx264', audioCodec: 'aac' },
    fields: ['subMode', 'gif', 'speed'],
  },
]

export function moduleByKey(key) {
  return videoToolModules.find((item) => item.key === key) || videoToolModules[0]
}
