const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
const root=path.join(os.tmpdir(),`ranpak-migration-test-${Date.now()}`),config=path.join(root,'config');fs.mkdirSync(config,{recursive:true});
fs.writeFileSync(path.join(config,'tools.json'),JSON.stringify({ai:{model:'model',apiKey:'secret'}}));
fs.writeFileSync(path.join(config,'cloud-sync.json'),JSON.stringify({username:'user',token:'token'}));
fs.writeFileSync(path.join(config,'ssh-tools.json'),JSON.stringify({profiles:[{id:'p1',name:'profile',secrets:{}}],folders:[],privates:[],remoteImportSources:[],presetCommands:[{id:'c1',name:'command'}]}));
fs.writeFileSync(path.join(config,'ssh-history.json'),JSON.stringify([{id:'h1',command:'ls'}]));
fs.writeFileSync(path.join(config,'dns.yaml'),'dns_access:\n  - name: dns\n    access_key_secret: secret\n');
process.env.RAN_PAK_RUNTIME_DIR=root;const store=require('../services/local-store');const safeStorage={isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value),decryptString:value=>Buffer.from(value).toString()};store.configure({safeStorage});
  try{const result=require('../services/storage-migration').migrate();assert.equal(result.migrated,true);assert.equal(store.get('app_config','ai').model,'model');assert.equal(store.list('ssh_profile').length,1);assert.equal(store.list('ssh_preset_command').length,1);assert.equal(store.list('dns_account').length,1);assert.equal(store.list('ssh_history').length,1);for(const file of ['tools.json','cloud-sync.json','ssh-tools.json','ssh-history.json','dns.yaml'])assert.equal(fs.existsSync(path.join(config,file)),false,'legacy source must be retired after migration');assert.equal(require('../services/tools-config').readToolsConfig().ai.model,'model');assert.equal(require('../services/config').getDnsAccounts().length,1);assert.equal(require('../services/storage-migration').migrate().migrated,false);console.log('migration tests passed');}finally{store.close();fs.rmSync(root,{recursive:true,force:true});}
