const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {DatabaseSync}=require('node:sqlite');
const store=require('../services/local-store');
const safeStorage={isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value),decryptString:value=>Buffer.from(value).toString()};
const root=path.join(os.tmpdir(),`ranpak-storage-test-${Date.now()}`),a=path.join(root,'a'),b=path.join(root,'b');
function use(dir){store.close();process.env.RAN_PAK_RUNTIME_DIR=dir;store.configure({safeStorage});store.init();store.setMeta('active_sync_space','space');}
function operation(row,seq){return{opId:row.op_id,deviceId:row.device_id,entityType:row.entity_type,entityId:row.entity_id,parentOpId:row.parent_op_id,mergeParents:JSON.parse(row.merge_parents||'[]'),contentHash:row.content_hash,deleted:Boolean(row.deleted),seq,createdAt:new Date(row.created_at).toISOString()};}
try{
  use(a);store.put('ssh_profile','one',{value:'base'});const base=store.pending('space').at(-1);
  use(b);store.applyRemote('space',operation(base,1),{value:'base'});store.put('ssh_profile','one',{value:'b'});const branch=store.pending('space').at(-1);
  use(a);store.markSynced('space',base.op_id,1);store.put('ssh_profile','one',{value:'a'});assert.equal(store.applyRemote('space',operation(branch,2),{value:'b'}).conflict,true);const conflict=store.conflicts('space')[0];store.resolveConflict(conflict.id,'local');const resolution=store.pending('space').at(-1);
  use(b);store.markSynced('space',branch.op_id,2);assert.equal(store.applyRemote('space',operation(resolution,3),{value:'a'}).resolved,true);assert.deepEqual(store.get('ssh_profile','one'),{value:'a'});assert.equal(store.conflicts('space').length,0);
  const before=store.pending('space').length;store.put('ssh_profile','one',{value:'a'});assert.equal(store.pending('space').length,before,'unchanged writes must not create operations');store.remove('ssh_profile','one');assert.equal(store.pending('space').at(-1).deleted,1);assert.equal(store.get('ssh_profile','one'),null);
  assert.equal(store.list('ssh_profile').length,0,'tombstones must be hidden from normal reads');
  store.setCursor('server-a:user:key',9);store.setCursor('server-b:user:key',4);assert.equal(store.getCursor('server-a:user:key'),9);assert.equal(store.getCursor('server-b:user:key'),4);
  use(a);store.put('local_storage','branch-doc',{value:'root'},{opId:'root-op',syncSpaceId:'space',force:true});store.put('local_storage','branch-doc',{value:'local-a'},{opId:'branch-a',syncSpaceId:'space',force:true});
  const remote=(opId,parent,value,seq)=>({opId,deviceId:'remote',entityType:'local_storage',entityId:'branch-doc',parentOpId:parent,mergeParents:[],contentHash:store.hash(JSON.stringify(value)),deleted:false,seq,createdAt:new Date().toISOString()});
  assert.equal(store.applyRemote('space',remote('branch-b','root-op',{value:'remote-b'},10),{value:'remote-b'}).conflict,true);assert.deepEqual(store.heads('space','local_storage','branch-doc').map(row=>row.op_id).sort(),['branch-a','branch-b']);
  assert.equal(store.applyRemote('space',remote('branch-c','branch-b',{value:'remote-c'},11),{value:'remote-c'}).branchAdvanced,true);assert.deepEqual(store.heads('space','local_storage','branch-doc').map(row=>row.op_id).sort(),['branch-a','branch-c'],'advancing one conflict branch must preserve the other branch');assert.deepEqual(store.get('local_storage','branch-doc'),{value:'local-a'},'remote conflict branch must not overwrite the visible local branch');
  assert.equal(store.applyRemote('space',remote('branch-d','root-op',{value:'remote-d'},12),{value:'remote-d'}).conflict,true);const multi=store.conflicts('space').find(item=>item.entity_id==='branch-doc');assert.equal(multi.branches.length,3,'all three offline branches must remain available to conflict resolution');const multiResolution=store.resolveConflict(multi.id,'local');assert.equal(JSON.parse(store.pending('space').find(row=>row.op_id===multiResolution.opId).merge_parents).length,3,'resolution must merge every current branch');
  store.setMeta('active_sync_space','old-account');store.setMeta('active_sync_space','');store.put('local_storage','unbound-edit',{value:true});assert.equal(store.pending('old-account').some(row=>row.entity_id==='unbound-edit'),false,'unbound edits must not leak into the prior account');assert.equal(store.pending('').some(row=>row.entity_id==='unbound-edit'),false,'unbound edits must wait for an account baseline instead of creating redundant operations');assert.equal(store.isSyncable('local_storage','ran-pak.badge-print.history'),false,'device-local image paths must never be synchronized');
  store.close();const legacyRoot=path.join(root,'legacy-pk'),legacyData=path.join(legacyRoot,'data');fs.mkdirSync(legacyData,{recursive:true});const legacyDb=new DatabaseSync(path.join(legacyData,'ranpak.db'));legacyDb.exec("CREATE TABLE change_log(op_id TEXT PRIMARY KEY,sync_space_id TEXT NOT NULL DEFAULT '',device_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,parent_op_id TEXT,merge_parents TEXT,payload TEXT NOT NULL,content_hash TEXT NOT NULL,deleted INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,sync_state TEXT NOT NULL DEFAULT 'pending',server_seq INTEGER)");legacyDb.close();process.env.RAN_PAK_RUNTIME_DIR=legacyRoot;store.init();assert.deepEqual(store.init().prepare('PRAGMA table_info(change_log)').all().filter(column=>column.pk).sort((x,y)=>x.pk-y.pk).map(column=>column.name),['sync_space_id','op_id'],'change log primary key must be scoped by sync space');
  console.log('storage sync tests passed');
}finally{store.close();fs.rmSync(root,{recursive:true,force:true});}
